version: "3.8"
networks:
  test:

services:
  java:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - test

  db:
    platform: linux/x86_64
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=uvds
    restart: always
    networks:
      - test